.pybuda-backend-silicon-gs-e150-perf-fp16:
  extends: .backend-gs-common
  stage: perf-gs-e150-fp16
  rules:
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /\[perf\]/)
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /\[perf_gs\]/)
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /\[perf_gs_e150_fp16\]/)
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /\[no_ci_perf\]/)
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /\[no_ci_perf_gs\]/)
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /\[no_ci_perf_gs_e150_fp16\]/)
    - if: ($CI_COMMIT_REF_NAME == "main" && $CI_JOB_DESCRIPTION == "pybuda-nightly")
  timeout: 60m
  variables:
    PYTEST_CURRENT_TEST: $CI_JOB_NAME
  tags:
    - gs-1-card
    - e150
    - performance
  script:
    - !reference [.common_prep, script]
    - !reference [.lib_gl_package, script]
  artifacts:
    paths:
      - /builds/tenstorrent/pybuda/*-perf.json
      - "*netlist.yaml"
  after_script:
    - ci/upload-perf-test.py -b gitlab-pipeline-$CI_PIPELINE_ID --job_name $CI_JOB_NAME
    # Move netlist(s) to root so that they'll be in root of artifacts - this runs before artifacts are saved
    - mv pytest_ci_out/$CI_JOB_NAME/*netlist.yaml ./
  
pybuda-silicon-gs-e150-perf-resnet:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m resnet -c resnet50 -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-mobilenet-v1:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m mobilenet_v1 -c 224 -df Fp16_b -mf HiFi2 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-mobilenet-v2:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m mobilenet_v2 -c 224 -df Fp16_b -mf HiFi2 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-mobilenet-v3:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m mobilenet_v3_timm -c large -df Fp16_b -mf HiFi2 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-vovnet-v2:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m vovnet_v2 -c 39 -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-openpose-body:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - git submodule update --init --checkout --depth 1 -f third_party/confidential_customer_models
    - pybuda/test/benchmark/benchmark.py -m openpose_osmr_body -c 2d -df Fp16 -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-openpose-hand:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - git submodule update --init --checkout --depth 1 -f third_party/confidential_customer_models
    - pybuda/test/benchmark/benchmark.py -m openpose_hand -c basic -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-hrnet:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m hrnet -c v2_w64 -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-yolo-v3:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - git submodule update --init --checkout --depth 1 -f third_party/confidential_customer_models
    - pybuda/test/benchmark/benchmark.py -m yolo_v3 -c default -mb 32 -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-yolo-v5:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m yolo_v5 -c s -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-inception-v4:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m inception_v4 -c 224 -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-unet:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m unet -c 256 -mb 48 -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-vit:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m vit -c base -df Fp16_b -mf HiFi2 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-deit:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m deit -c base -df Fp16_b -mf HiFi2 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-bert-large:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m bert -c large_tc -df Fp16_b -mf HiFi3 -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-whisper:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m whisper -c small --loop_count 1 -mb 1 -df Fp16_b -mf HiFi3 --single-thread --generative -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-t5-large:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m t5 -c large --loop_count 1 -mb 1 -df Fp16_b -mf HiFi3 --single-thread --generative -o $CI_JOB_NAME-perf.json

pybuda-silicon-gs-e150-perf-flan-t5-large:
  extends: .pybuda-backend-silicon-gs-e150-perf-fp16
  script:
    - !reference [.pybuda-backend-silicon-gs-e150-perf-fp16, script]
    - pybuda/test/benchmark/benchmark.py -m flan_t5 -c large --loop_count 1 -mb 1 -df Fp16_b -mf HiFi3 --single-thread --generative -o $CI_JOB_NAME-perf.json
