.silicon-wh-b0-perf-fp16-manual:
  extends: .backend-wh-b0-common
  rules:
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /\[no_ci_perf_manual_wh\]/)
  timeout: 240m
  stage: perf-wh-b0-silicon-release
  allow_failure: false
  variables:
    BACKEND_ARCH_NAME: "wormhole_b0"
    LD_LIBRARY_PATH: "versim/wormhole_b0/lib:versim/wormhole_b0/lib/ext"
    PYTEST_ADDOPTS: "-svv --silicon-only --durations=10 --durations-min=10 --junitxml=$CI_PROJECT_DIR/test-results/report.xml"
    PYTEST_CURRENT_TEST: $CI_JOB_NAME
  tags:
    - wh-1-card
    - n150
    - performance
  artifacts:
    paths:
      - /builds/tenstorrent/pybuda/*-perf.json
      - "*netlist.yaml"
    expire_in: 1 day
    when: always
  script:
    - !reference [.common_prep, script]
    - !reference [.retry_on_hang_wh, script]
    - !reference [.lib_gl_package, script]
  after_script:
    - ci/upload-perf-test.py -b gitlab-pipeline-$CI_PIPELINE_ID --job_name $CI_JOB_NAME
    # Move netlist(s) to root so that they'll be in root of artifacts - this runs before artifacts are saved
    - mv pytest_ci_out/$CI_JOB_NAME/*netlist.yaml ./

pybuda-silicon-wh-b0-perf-all:
  extends: .silicon-wh-b0-perf-fp16-manual
  script:
    - !reference [.silicon-wh-b0-perf-fp16-manual, script]
    - git submodule update --init --checkout --depth 1 -f third_party/confidential_customer_models
    - source pybuda/test/benchmark/run_benchmark_wh_release