name: Build artifacts

on:
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: "python3.10"

jobs:
  build-artifacts:
    strategy:
      matrix:
        arch: ["grayskull"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update submodule
        run: git submodule update --init --recursive
      - name: Build for ${{ matrix.arch }}
        run: source env_for_silicon.sh