name: "Post commit workflow"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit