name: Post commit workflow

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    secrets: inherit